apiVersion: v1
kind: Service
metadata:
  name: baolm-capstone-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: capstone
      protocol: TCP
  selector:
    app: baolm-capstone