apiVersion: v1
kind: Service
metadata:
  name: anhpham-capstone-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: anhpham-capstone
      protocol: TCP
  selector:
    app: anhpham-capstone